# Build Geth in a stock Go builder container
FROM centos:7 as builder

RUN yum install -y gcc git make wget; \
    wget https://go.dev/dl/go1.16.15.linux-amd64.tar.gz; \
    tar -C /usr/local -xzf go1.16.15.linux-amd64.tar.gz; \
    export PATH=$PATH:/usr/local/go/bin; \
    ln  -s /usr/local/go/bin/go /bin/go 

ADD . /go-ethereum
RUN cd /go-ethereum && make geth

# Pull Geth into a second stage deploy alpine container
FROM centos:7

COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/

EXPOSE 8545 8546 30303 30303/udp
ENTRYPOINT ["geth"]
